### ISSUE TITLE
"Array" Appearing Beside Approve/Decline Buttons

### ISSUE THREAD

**Issue by mrjarbenne** [r-a-y/bp-site-moderation#5]
I believe this occurred after a recent BP update (Maybe 5.1.0)

![2020-01-08_14-15-48](https://user-images.githubusercontent.com/480667/72008539-12912380-3222-11ea-8ab5-6b81b508678f.png)

**Comment by r-a-y** [comment]
This is a BuddyPress bug that is fixed in the upcoming 6.0.0 release:
https://buddypress.trac.wordpress.org/ticket/8147

I previously patched production with that patch, but since the update to 5.1.2, the code was removed.  I've just re-patched the production install, so we should be good for now until there is another 5.x maintenance release.
